import { jaJP } from "@clerk/localizations";  // https://clerk.com/docs/nextjs/localization?utm_source=www.google.com&utm_medium=referral&utm_campaign=none
import { ClerkProvider } from "@clerk/nextjs"; 
import { Inter } from "next/font/google"; 
import "./globals.css";

const inter = Inter({ subsets:["latin"] });   // Inter関数としてlatin 設定 interに入れる

export const metadata = {   // metadataとしてtitleとdescriptionを指定
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,   // childrenという名前のプロップを定義  プロップ:親コンポーネントから子コンポーネントにデータを渡すメカニズム
}:{
  children:React.ReactNode;   // それはReact.ReactNode型とした
}) {    // コンポーネントのロジック
  return (
    <ClerkProvider localization={jaJP}> {/* ClerkProvider:Clerk.jsライブラリーをReactで使うためのコンポーネント localizationは地域を指す*/}
      <html lang="ja">      {/* 日本語指定 */}
        <body className={inter.className}>
          <main className="mx-auto flex min-h-screen max-w-5xl flex-col place-content-center justify-between md:p-12">
            {/* mx-auto:{margin-left: auto,margin-right:auto}, flex:{display:flex}, min-h-screen:{min-height:100vh}, 
            max-w-5xl:{max-width:80rem}, flex-col:{flex-direction:column}, place-content-center:{justify-content:center,align-items:center},
            justify-between:{justify-content:space-between}, md:{p-12} */}
            {children}      {/* children表示 */}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}